#!/bin/bash

python3 11_Electra_Sector_Classification.py
python3 12_Electra_Sector_Classification_as_Regression.py
python3 13_Electra_Query_Type_Classification.py
python3 14_Electra_QueryType_Classification_as_Regression.py
